### PR TITLE
Update to Scala 3.0.0-RC3

### PR DESCRIPTION
**Pull request by vasilmkd**
Also fixed some old sbt syntax.

### CODE REVIEW

**Comment by travisbrown** [comment]
@larsrh @rossabaker Any objections to merging this and publishing a 2.1.4? I'm happy to do that today.

(Asking because it would make publishing a new Circe milestone easier for me.)

**Comment by vasilmkd** [comment]
I think this might be the last blocker for a new circe release and in turn http4s. 😄

**Comment by travisbrown** [comment]
@vasilmkd I really should have tried to set up the Circe build so that Scala 3 releases weren't blocked on this library, since I'm not running most tests for most modules on Scala 3 anyway at the moment, but right, given that I never got around to that, this is the one thing we're still waiting on. :smile:

**Comment by vasilmkd** [comment]
I can help out with that if you're willing to give me some pointers.

**Comment by travisbrown** [comment]
@vasilmkd Thanks, but it's more of a workaround that would have added value six months ago. Since this RC / milestone process is almost over, I'm not sure it's worth it now. I think we can just wait for this release (which I can do today) and then I'll publish Circe 0.14.0-M6.

**Review by larsrh — APPROVED** [review]
Thanks, LGTM!

**Comment by larsrh** [comment]
@travisbrown Feel free to run the release process.

**Comment by travisbrown** [comment]
2.1.4 is on its way to Maven Central. Thanks @vasilmkd!

**Pull request merged**
