### PR TITLE
Miscellaneous updates

### PR DESCRIPTION
**Pull request by travisbrown**
This PR does several unrelated things because I'm too lazy to line them all up as individual PRs for this project:

* Updates Jekyll, fixing the CI failure in #39 (I think / hope).
* Updates sbt-microsites, like #34, but unlike #34 it actually does the work that's necessary for this update.
* Includes @jhnsmth's commit from #39 (so please don't squash).
* Actually turns on Scalafmt and uses the standard Cats config (previously there was only config—it wasn't actually enabled).
* Updates Scala versions.
* Turns on cross-building for Scala.js (1.0.0-RC2 and 0.6).

### CODE REVIEW

**Comment by travisbrown** [comment]
Once this is merged I can publish either 1.0.0-RC2 or 1.0.0.

**Comment by travisbrown** [comment]
@larsrh Mind if I go ahead and publish a 1.0.0-RC2 with this?

**Comment by larsrh** [comment]
Not at all, go ahead.

**Comment by jhnsmth** [comment]
:+1: Thanks Travis!

**Pull request merged**
