### PR TITLE
Add Dotty 0.27.0-RC1 to cross-build

### PR DESCRIPTION
**Pull request by felixbr**
Hi,

this adds the latest dotty version to the cross-build. As far as I could tell it's the last dependency blocking a `circe` cross-build for Dotty `0.27.0-RC1`.

I left the `0.26.0-RC1` version in the cross-build but it would also be reasonable to remove it as Dotty is moving quickly.

It would be really nice to publish version `2.0.1` for Dotty `0.27.0-RC1` as well or at least as a new version, so I can try the `circe` cross-build again.

Cheers
~ Felix

### CODE REVIEW

**Comment by felixbr** [comment]
CI is green for `0.27.0-RC1` but failed for `0.26.0-RC1`, which I didn't touch. That's awkward...

**Comment by larsrh** [comment]
Sorry, I missed this PR. Let's just drop 0.27. I can do a back-port release of 2.0.1.

**Comment by larsrh** [comment]
Release is out, Travis CI is still catching up. We can merge this if green.

**Comment by felixbr** [comment]
Thank you 😊

**Pull request merged**
